# Generated by Django 5.0.6 on 2024-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_learningsessioncompletedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='example',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
