# Generated by Django 5.0.6 on 2024-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcard_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='learnt',
            field=models.BooleanField(default=False),
        ),
    ]
