# Generated by Django 5.0.6 on 2024-10-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_flashcard_learnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations/'),
        ),
    ]
